apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "00"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-hub
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: "10.1.1"
      helm:
        releaseName: argocd
        valueFiles:
          - $values/platform/upstream-values/argocd-values.yaml
    - repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
