apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-hub
  source:
    repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
    targetRevision: main
    path: platform/gateway-routes/hub
    directory:
      exclude: "{grafana,prometheus,alertmanager}-httproute.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m