grafana:
  adminPassword: kagura12
  
  env:
    GF_SERVER_ROOT_URL: http://aa-123124710.ap-northeast-1.elb.amazonaws.com/grafana/
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClassName: ebs-csi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    path: /grafana
    pathType: Prefix

  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 1Gi

prometheus:
  prometheusSpec:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
    externalUrl: http://aa-123124710.ap-northeast-1.elb.amazonaws.com/prometheus/
    routePrefix: /prometheus
    retention: 2d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: ebs-csi
          resources:
            requests:
              storage: 1Gi

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 800Mi

  ingress:
    enabled: true
    ingressClassName: nginx
    path: 
      - /prometheus
    pathType: Prefix

alertmanager:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi