grafana:
  adminPassword: kagura12
  deploymentStrategy:
    type: Recreate
  
  # env:
  #   GF_SERVER_ROOT_URL: http://aa-123124710.ap-northeast-1.elb.amazonaws.com/grafana/
  #   GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClassName: ebs-csi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "internal-ca-issuer"
    hosts:
      - grafana.phuoctd6.shop
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.phuoctd6.shop

  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 700Mi

prometheus:
  prometheusSpec:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
    retention: 2d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: ebs-csi
          resources:
            requests:
              storage: 1Gi

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 800Mi

  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "internal-ca-issuer"
    hosts:
      - prometheus.phuoctd6.shop
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.phuoctd6.shop

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "internal-ca-issuer"
    hosts:
      - alertmanager.phuoctd6.shop
    paths:
      - /
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.phuoctd6.shop

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    # requests:
    #   cpu: 50m
    #   memory: 64Mi