args:
  - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
  - --metric-resolution=15s
  - --kubelet-insecure-tls

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi