apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            role: spoke
  template:
    metadata:
      name: 'cilium-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "00"
    spec:
      project: platform-infra
      sources:
        - repoURL: https://helm.cilium.io/
          chart: cilium
          targetRevision: "1.16.0"
          helm:
            releaseName: cilium
            valueFiles:
              - $values/platform/upstream-values/cilium-values.yaml
        - repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
  # ignoreDifferences:
  #   - group: monitoring.coreos.com
  #     kind: ServiceMonitor
  #     name: cilium-agent
  #     jsonPointers:
  #       - /spec/endpoints/0/relabelings
  #   - group: monitoring.coreos.com
  #     kind: ServiceMonitor
  #     name: hubble
  #     jsonPointers:
  #       - /spec/endpoints/0/relabelings