apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            role: spoke
  template:
    metadata:
      name: 'metrics-server-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: platform-infra
      sources:
        - repoURL: https://kubernetes-sigs.github.io/metrics-server/
          chart: metrics-server
          targetRevision: "3.13.1"
          helm:
            releaseName: metrics-server
            valueFiles:
              - $values/platform/upstream-values/metrics-server-values.yaml
        - repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true