apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-servicemonitors
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-infra
  source:
    repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
    targetRevision: main
    path: platform/monitoring-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true