apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-infra
  source:
    repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
    targetRevision: main
    path: argocd/apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true      # remove an Application here if its file is deleted from git
      selfHeal: true    # revert manual kubectl/helm edits back to git state
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
