{{- if and .Values.database.createSecret (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-app.databaseSecretName" . }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
{{- end }}