apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-configs
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-role: workload
  template:
    metadata:
      name: 'cert-manager-configs-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform-infra
      source:
        repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
        targetRevision: main
        path: platform/cert-manager
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
