apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-servicemonitors
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            role: workload
  template:
    metadata:
      name: 'cilium-servicemonitors-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "25"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform-infra
      source:
        repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
        targetRevision: main
        path: platform/monitoring-configs
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
