apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20" 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-infra
  source:
    repoURL: https://github.com/trandinhphuoc1198/k8s_ArgoCD.git
    targetRevision: main
    path: cert-manager-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true