apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

labels:
- includeSelectors: false
  pairs:
    managed-by: kustomize
    project: fastapi-k8s
